language: python
python:
  - 3.7
  - 3.8

cache:
  pip: true
  apt: true
  directories:
    - $HOME/.pip-cache

install:
  - pip install -e .
  
script:
  - pytest

notifications:
  email:
      on_success: never # change
      on_failure: never # always